env:
  global:
    - CC_TEST_REPORTER_ID=b2258e835c1b69dc14aef5dcb4d3e0b9153810b0e4e86cb702955164a514043f
language: ruby
cache: bundler
rvm:
  - 2.4.2
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: "bundle exec rspec"     
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
